name: Compile LaTeX

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '*.tex'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show Environment
      run: |
        printenv | sort

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install -y texlive texlive-latex-extra

    - name: Compile LaTeX to PDF
      run: |
        pdflatex -interaction=nonstopmode chapter4.tex

    - name: Generate release tag
      id: tag
      run: |
        release_tag=$(date +"%Y.%m.%d_%H-%M")
        git tag $release_tag
        git push origin $release_tag
        echo release_tag=$release_tag >> $GITHUB_OUTPUT

    - name: Release PDF
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          chapter4.pdf
